
course: "CS190J"
qtr: "S18"
quarter: "Spring 2018"
ta_list: ""
ta_list_full: ""
instructor: "Mirza,Conrad,Wang"
piazza: https://piazza.com/class/tbd

github_url: https://github.com/ucsb-cs190j-s18/ucsb-cs190j-s18.github.io
course_site: https://ucsb-cs190j-s18.github.io


start_week: 1
start_date: 2018-04-01 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true


cal_dates: >
  [
  {"label":"First day of Spring Quarter", "date":"2018-04-02" },
  {"label":"Univ Holiday", "date":"2018-05-28" },
  {"label":"Last day of instruction", "date":"2018-06-08" },
  {"label":"Finals Begin", "date":"2018-06-09" },
  {"label":"Finals End", "date":"2018-06-09" },
  {"label":"Last day to drop (11pm)", "date":"2018-04-27" },	
  ]



kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor


timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


